from __future__ import annotations

import json
from typing import Any


PROTOCOL_SCHEMA_VERSION = "1.0"
CAPABILITIES_SCHEMA_VERSION = "1.0"

EXIT_SUCCESS = 0
EXIT_REFUSED = 2
EXIT_TESTS_FAILED = 3
EXIT_SECURITY = 4
EXIT_INTERNAL = 5

ERROR_CODES = (
    "GIT_NOT_REPOSITORY",
    "GIT_DIRTY",
    "FILE_OUTSIDE_PROJECT",
    "FILE_NOT_FOUND",
    "PARSE_ERROR",
    "TARGET_NOT_FOUND",
    "TARGET_AMBIGUOUS",
    "TARGET_UNSUPPORTED",
    "DOCSTRING_EXISTS",
    "ANNOTATION_REQUIRED",
    "ANNOTATION_INVALID",
    "ANNOTATION_EXISTS",
    "RETURN_ANNOTATION_REQUIRED",
    "RETURN_ANNOTATION_INVALID",
    "RETURN_ANNOTATION_NOT_FOUND",
    "RETURN_ANNOTATION_MISMATCH",
    "PARAMETER_REQUIRED",
    "PARAMETER_NOT_FOUND",
    "PARAMETER_ANNOTATION_EXISTS",
    "PARAMETER_KIND_UNSUPPORTED",
    "PARAMETER_ANNOTATION_REQUIRED",
    "PARAMETER_ANNOTATION_INVALID",
    "PARAMETER_ANNOTATION_NOT_FOUND",
    "PARAMETER_ANNOTATION_MISMATCH",
    "DECORATOR_REQUIRED",
    "DECORATOR_INVALID",
    "DECORATOR_POSITION_REQUIRED",
    "DECORATOR_POSITION_INVALID",
    "DECORATOR_NOT_FOUND",
    "DECORATOR_POSITION_MISMATCH",
    "DECORATOR_TARGET_UNSUPPORTED",
    "DECORATOR_ALREADY_EXISTS",
    "DECORATOR_CONFLICT",
    "IMPORT_STATEMENT_REQUIRED",
    "IMPORT_STATEMENT_INVALID",
    "IMPORT_MULTIPLE_BINDINGS_UNSUPPORTED",
    "IMPORT_WILDCARD_UNSUPPORTED",
    "IMPORT_RELATIVE_UNSUPPORTED",
    "IMPORT_ALREADY_EXISTS",
    "IMPORT_BINDING_CONFLICT",
    "IMPORT_PLACEMENT_UNSUPPORTED",
    "IMPORT_NOT_FOUND",
    "IMPORT_AMBIGUOUS",
    "IMPORT_SCOPE_UNSUPPORTED",
    "UNSUPPORTED_OPERATION",
    "UNKNOWN_SQLITE_OPERATION",
    "HASH_MISMATCH",
    "LEGACY_UNVERIFIABLE",
    "TESTS_FAILED",
    "DATABASE_ERROR",
    "ROLLBACK_NOT_AVAILABLE",
    "OPERATION_ID_REQUIRED",
    "OPERATION_ID_INVALID",
    "OPERATION_NOT_FOUND",
    "ROLLBACK_SELECTOR_CONFLICT",
    "ROLLBACK_ALREADY_APPLIED",
    "ROLLBACK_RECORD_NOT_ALLOWED",
    "PROJECT_MISMATCH",
    "INTERNAL_ERROR",
)

EXIT_CODE_BY_ERROR_CODE = {
    "GIT_NOT_REPOSITORY": EXIT_REFUSED,
    "GIT_DIRTY": EXIT_REFUSED,
    "FILE_OUTSIDE_PROJECT": EXIT_REFUSED,
    "FILE_NOT_FOUND": EXIT_REFUSED,
    "PARSE_ERROR": EXIT_REFUSED,
    "TARGET_NOT_FOUND": EXIT_REFUSED,
    "TARGET_AMBIGUOUS": EXIT_REFUSED,
    "TARGET_UNSUPPORTED": EXIT_REFUSED,
    "DOCSTRING_EXISTS": EXIT_REFUSED,
    "ANNOTATION_REQUIRED": EXIT_REFUSED,
    "ANNOTATION_INVALID": EXIT_REFUSED,
    "ANNOTATION_EXISTS": EXIT_REFUSED,
    "RETURN_ANNOTATION_REQUIRED": EXIT_REFUSED,
    "RETURN_ANNOTATION_INVALID": EXIT_REFUSED,
    "RETURN_ANNOTATION_NOT_FOUND": EXIT_REFUSED,
    "RETURN_ANNOTATION_MISMATCH": EXIT_REFUSED,
    "PARAMETER_REQUIRED": EXIT_REFUSED,
    "PARAMETER_NOT_FOUND": EXIT_REFUSED,
    "PARAMETER_ANNOTATION_EXISTS": EXIT_REFUSED,
    "PARAMETER_KIND_UNSUPPORTED": EXIT_REFUSED,
    "PARAMETER_ANNOTATION_REQUIRED": EXIT_REFUSED,
    "PARAMETER_ANNOTATION_INVALID": EXIT_REFUSED,
    "PARAMETER_ANNOTATION_NOT_FOUND": EXIT_REFUSED,
    "PARAMETER_ANNOTATION_MISMATCH": EXIT_REFUSED,
    "DECORATOR_REQUIRED": EXIT_REFUSED,
    "DECORATOR_INVALID": EXIT_REFUSED,
    "DECORATOR_POSITION_REQUIRED": EXIT_REFUSED,
    "DECORATOR_POSITION_INVALID": EXIT_REFUSED,
    "DECORATOR_NOT_FOUND": EXIT_REFUSED,
    "DECORATOR_POSITION_MISMATCH": EXIT_REFUSED,
    "DECORATOR_TARGET_UNSUPPORTED": EXIT_REFUSED,
    "DECORATOR_ALREADY_EXISTS": EXIT_REFUSED,
    "DECORATOR_CONFLICT": EXIT_REFUSED,
    "IMPORT_STATEMENT_REQUIRED": EXIT_REFUSED,
    "IMPORT_STATEMENT_INVALID": EXIT_REFUSED,
    "IMPORT_MULTIPLE_BINDINGS_UNSUPPORTED": EXIT_REFUSED,
    "IMPORT_WILDCARD_UNSUPPORTED": EXIT_REFUSED,
    "IMPORT_RELATIVE_UNSUPPORTED": EXIT_REFUSED,
    "IMPORT_ALREADY_EXISTS": EXIT_REFUSED,
    "IMPORT_BINDING_CONFLICT": EXIT_REFUSED,
    "IMPORT_PLACEMENT_UNSUPPORTED": EXIT_REFUSED,
    "IMPORT_NOT_FOUND": EXIT_REFUSED,
    "IMPORT_AMBIGUOUS": EXIT_REFUSED,
    "IMPORT_SCOPE_UNSUPPORTED": EXIT_REFUSED,
    "UNSUPPORTED_OPERATION": EXIT_REFUSED,
    "UNKNOWN_SQLITE_OPERATION": EXIT_REFUSED,
    "HASH_MISMATCH": EXIT_SECURITY,
    "LEGACY_UNVERIFIABLE": EXIT_SECURITY,
    "TESTS_FAILED": EXIT_TESTS_FAILED,
    "DATABASE_ERROR": EXIT_INTERNAL,
    "ROLLBACK_NOT_AVAILABLE": EXIT_REFUSED,
    "OPERATION_ID_REQUIRED": EXIT_REFUSED,
    "OPERATION_ID_INVALID": EXIT_REFUSED,
    "OPERATION_NOT_FOUND": EXIT_REFUSED,
    "ROLLBACK_SELECTOR_CONFLICT": EXIT_REFUSED,
    "ROLLBACK_ALREADY_APPLIED": EXIT_REFUSED,
    "ROLLBACK_RECORD_NOT_ALLOWED": EXIT_REFUSED,
    "PROJECT_MISMATCH": EXIT_REFUSED,
    "INTERNAL_ERROR": EXIT_INTERNAL,
}


class ProtocolError(RuntimeError):
    def __init__(self, message: str, *, code: str = "INTERNAL_ERROR", details: dict[str, Any] | None = None) -> None:
        super().__init__(message)
        self.code = code
        self.details = details or {}

    @property
    def exit_code(self) -> int:
        return EXIT_CODE_BY_ERROR_CODE.get(self.code, EXIT_INTERNAL)

    def to_payload(self) -> dict[str, Any]:
        return {
            "code": self.code,
            "message": str(self),
            "details": self.details,
        }


def dump_json(payload: dict[str, Any]) -> str:
    return json.dumps(payload, indent=2, ensure_ascii=False)


def build_protocol_response(
    *,
    command: str,
    ok: bool,
    status: str,
    error: dict[str, Any] | None = None,
    result: dict[str, Any] | None = None,
    meta: dict[str, Any] | None = None,
) -> dict[str, Any]:
    return {
        "protocol_schema_version": PROTOCOL_SCHEMA_VERSION,
        "command": command,
        "ok": ok,
        "status": status,
        "error": error,
        "result": result,
        "meta": meta or {},
    }


def build_capabilities_payload(
    operations: list[dict[str, Any]],
    commands: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    payload = {
        "protocol_schema_version": PROTOCOL_SCHEMA_VERSION,
        "capabilities_schema_version": CAPABILITIES_SCHEMA_VERSION,
        "operations": operations,
    }
    if commands is not None:
        payload["commands"] = commands
    return payload
